---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-DBI-ClassGenerator
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: 0
  DBI: 0
  File::Temp: 0.19
  Test::More: 0
version: 1.04
x_resource:
  repository: https://github.com/DrHyde/perl-modules-Class-DBI-ClassGenerator
